# Generated by Django 4.2.4 on 2023-09-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_course_recent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam.Question.answer+', to='exam.answer'),
        ),
        migrations.AlterField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exam.question'),
        ),
    ]
