# Generated by Django 4.2.4 on 2023-09-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_course_description_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(blank=True, to='exam.answer')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('passcode', models.CharField(max_length=8)),
                ('exams', models.ManyToManyField(blank=True, to='exam.examination')),
            ],
        ),
    ]
