# Generated by Django 4.2.4 on 2023-09-06 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_examination_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='questions',
            field=models.ManyToManyField(blank=True, to='exam.question'),
        ),
        migrations.AddField(
            model_name='examination',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 12, 8, 55, 654928, tzinfo=datetime.timezone.utc)),
        ),
    ]
