# Generated by Django 4.2.4 on 2023-09-06 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_examination_questions_examination_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
