# Generated by Django 4.2.4 on 2023-09-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_examination_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='examination',
            name='status',
            field=models.CharField(default='running', max_length=9),
        ),
    ]
