# Generated by Django 4.2.4 on 2023-09-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_course_time_alter_examination_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='submit',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
