# Generated by Django 4.2.4 on 2023-09-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_course_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='submit',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(),
        ),
    ]
