# Generated by Django 4.2.4 on 2023-09-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_course_submit_alter_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
