# Generated by Django 4.2.4 on 2023-09-09 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_studentdetails_reg_alter_course_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='exams/images/'),
        ),
    ]
