# Generated by Django 4.2.4 on 2023-10-05 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.studentdetails'),
        ),
    ]
