# Generated by Django 4.2.4 on 2023-10-05 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_examination_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='student',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.studentdetails'),
        ),
    ]
