# Generated by Django 4.2.4 on 2023-10-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_alter_examination_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
