# Generated by Django 4.2.4 on 2023-08-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('Phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('Home_address', models.CharField(blank=True, max_length=250, null=True)),
                ('Bvn', models.CharField(blank=True, max_length=20, null=True)),
                ('Nin', models.CharField(blank=True, max_length=20, null=True)),
                ('Marital_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
