# Generated by Django 4.2.4 on 2023-08-16 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_first_name_userapplication_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Account_number',
        ),
    ]
