# Generated by Django 4.2.4 on 2023-08-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
