# Generated by Django 4.2.4 on 2023-08-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApplication',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Bvn',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Home_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Identification',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Marital_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Nationality',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Next_of_kin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Nin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Profile_pic',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pin',
        ),
    ]
