# Generated by Django 4.2.4 on 2023-09-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_userapplication_remove_user_bvn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Phone_number',
        ),
    ]
